"""FastAPI router for the Frontier-to-Local Orchestrator.

This router handles the handoff between the frontier model (which generates
analytical SQL plans based on schemas) and the local engine (which executes
SQL plans against raw data via Tier 1 MCP tools).

Endpoints:
- POST /v1/orchestrator/execute_sql — Execute a SQL plan locally.
- GET  /v1/orchestrator/status/{execution_id} — Query execution status.
- GET  /v1/orchestrator/schemas — Return database schemas for frontier planning.
"""

from __future__ import annotations

import logging
import uuid
from typing import Annotated

from fastapi import APIRouter, HTTPException, status
from pydantic import BaseModel, ConfigDict, Field

from app.mcp.cloud_tools import CloudToolError, get_schema_info
from app.mcp.local_tools import SqlExecutionError, execute_raw_sql

logger = logging.getLogger("app.routers.orchestrator")
router = APIRouter(prefix="/v1/orchestrator", tags=["orchestrator"])

# ── Request / Response Schemas ───────────────────────────────────────


class SqlExecutionRequest(BaseModel):
    """Payload submitted by the frontier model for local SQL execution.

    The frontier model generates SQL plans based on schemas only — no PII
    or raw data should be present in this payload.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    sql: Annotated[
        str,
        Field(
            min_length=1,
            max_length=4096,
            description="Parameterized SQL statement to execute locally.",
        ),
    ]
    parameters: list[str | int | float | bool | None] | None = Field(
        default=None,
        description="Optional parameterized values for the SQL statement.",
    )
    plan_id: str | None = Field(
        default=None,
        description="Optional plan identifier from the frontier model for correlation.",
    )


class SqlExecutionResponse(BaseModel):
    """Response from successful local SQL execution."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    execution_id: str
    status: str
    row_count: int
    results: list[dict[str, object]]
    plan_id: str | None = None


class SqlExecutionErrorResponse(BaseModel):
    """Structured error response for failed SQL execution."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    status: str
    execution_id: str
    error_code: str
    detail: str
    plan_id: str | None = None


class SchemaResponse(BaseModel):
    """Database schema information for frontier model planning."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    tables: list[dict[str, object]]


class ExecutionStatusResponse(BaseModel):
    """Status of a previously submitted SQL execution."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    execution_id: str
    status: str  # "completed", "failed"
    row_count: int | None = None
    error_code: str | None = None
    error_message: str | None = None
    plan_id: str | None = None


# ── In-Memory Execution Store ────────────────────────────────────────
# Lightweight store for tracking execution status.
# In production this would be a persistent store (Redis/DB).

_execution_store: dict[str, dict[str, object]] = {}


# ── Route Handlers ───────────────────────────────────────────────────


@router.post(
    "/execute_sql",
    response_model=SqlExecutionResponse | SqlExecutionErrorResponse,
    status_code=status.HTTP_200_OK,
    responses={
        400: {
            "model": SqlExecutionErrorResponse,
            "description": "Invalid payload or SQL validation failure.",
        },
        500: {
            "model": SqlExecutionErrorResponse,
            "description": "Internal execution error.",
        },
    },
)
async def execute_sql_plan(
    payload: SqlExecutionRequest,
) -> SqlExecutionResponse | SqlExecutionErrorResponse:
    """Execute a SQL plan generated by the frontier model on the local engine.

    The frontier model generates analytical SQL plans based ONLY on schemas.
    This endpoint executes the plan against raw data using Tier 1 MCP tools.

    Args:
        payload: SQL execution request from the frontier model.

    Returns:
        SqlExecutionResponse on success or SqlExecutionErrorResponse on failure.
    """
    execution_id = uuid.uuid4().hex
    plan_id = payload.plan_id

    logger.info(
        "Received SQL execution request",
        extra={
            "execution_id": execution_id,
            "plan_id": plan_id,
            "sql_prefix": payload.sql[:80],
        },
    )

    # Store execution status as "running"
    _execution_store[execution_id] = {
        "status": "running",
        "plan_id": plan_id,
    }

    try:
        # Execute SQL via Tier 1 MCP tool
        results = execute_raw_sql(
            sql=payload.sql,
            parameters=payload.parameters,
        )

        row_count = len(results)
        logger.info(
            "SQL execution completed successfully",
            extra={
                "execution_id": execution_id,
                "row_count": row_count,
                "plan_id": plan_id,
            },
        )

        # Update execution store
        _execution_store[execution_id] = {
            "status": "completed",
            "row_count": row_count,
            "plan_id": plan_id,
        }

        return SqlExecutionResponse(
            execution_id=execution_id,
            status="completed",
            row_count=row_count,
            results=results,
            plan_id=plan_id,
        )

    except SqlExecutionError as exc:
        logger.warning(
            "SQL execution failed validation",
            extra={
                "execution_id": execution_id,
                "error_code": "SQL_VALIDATION_ERROR",
                "plan_id": plan_id,
            },
        )
        _execution_store[execution_id] = {
            "status": "failed",
            "error_code": "SQL_VALIDATION_ERROR",
            "error_message": str(exc),
            "plan_id": plan_id,
        }
        return SqlExecutionErrorResponse(
            status="failed",
            execution_id=execution_id,
            error_code="SQL_VALIDATION_ERROR",
            detail=str(exc),
            plan_id=plan_id,
        )

    except Exception as exc:  # noqa: BLE001
        logger.error(
            "SQL execution failed unexpectedly",
            extra={
                "execution_id": execution_id,
                "error_type": type(exc).__name__,
                "plan_id": plan_id,
            },
        )
        _execution_store[execution_id] = {
            "status": "failed",
            "error_code": "EXECUTION_ERROR",
            "error_message": str(exc),
            "plan_id": plan_id,
        }
        return SqlExecutionErrorResponse(
            status="failed",
            execution_id=execution_id,
            error_code="EXECUTION_ERROR",
            detail=str(exc),
            plan_id=plan_id,
        )


@router.get(
    "/status/{execution_id}",
    response_model=ExecutionStatusResponse,
    responses={404: {"description": "Execution not found"}},
)
def get_execution_status(
    execution_id: str,
) -> ExecutionStatusResponse:
    """Retrieve the status of a previously submitted SQL execution.

    Args:
        execution_id: The unique execution identifier returned by execute_sql_plan.

    Returns:
        ExecutionStatusResponse with current status.

    Raises:
        HTTPException(404): If the execution_id is not found.
    """
    record = _execution_store.get(execution_id)
    if record is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Execution {execution_id} not found.",
        )

    return ExecutionStatusResponse(
        execution_id=execution_id,
        status=record["status"],
        row_count=record.get("row_count"),
        error_code=record.get("error_code"),
        error_message=record.get("error_message"),
        plan_id=record.get("plan_id"),
    )


@router.get(
    "/schemas",
    response_model=SchemaResponse,
    description="Return database schemas for frontier model SQL planning.",
)
def get_database_schemas() -> SchemaResponse:
    """Return database schema information for frontier model SQL planning.

    This endpoint provides table and column metadata without exposing any
    data or PII, enabling the frontier model to generate accurate SQL plans.

    Returns:
        SchemaResponse containing table names and column metadata.
    """
    logger.info("Schema introspection requested by frontier model")

    try:
        schema_info = get_schema_info()
        tables = []
        for table_name in schema_info.get("tables", []):
            try:
                table_details = get_schema_info(table_name=table_name)
                tables.append(table_details)
            except CloudToolError as exc:
                logger.warning(
                    "Failed to introspect table schema",
                    extra={"table": table_name, "error": str(exc)},
                )

        return SchemaResponse(tables=tables)

    except CloudToolError as exc:
        logger.error(
            "Schema introspection failed",
            extra={"error_type": type(exc).__name__},
        )
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Schema introspection failed: {exc}",
        )
